# Generated by Django 3.2.3 on 2021-06-09 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
