# Generated by Django 3.2.3 on 2021-06-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210609_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_imagen', to='blog.post'),
        ),
    ]
