# Generated by Django 3.2.3 on 2021-06-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import negocio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('postada', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('votos', models.IntegerField(blank=True, default=0)),
                ('mision', models.CharField(blank=True, max_length=300, null=True)),
                ('vision', models.CharField(blank=True, max_length=300, null=True)),
                ('compartido', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True, unique=True)),
                ('sitio_web', models.URLField(blank=True, max_length=30, null=True, unique=True)),
                ('facebook', models.URLField(blank=True, max_length=30, null=True, unique=True)),
                ('instagram', models.URLField(blank=True, max_length=30, null=True, unique=True)),
                ('whatsapp', models.URLField(blank=True, max_length=30, null=True, unique=True)),
                ('telegram', models.URLField(blank=True, max_length=30, null=True, unique=True)),
                ('pais', models.CharField(default='Cuba', max_length=25)),
                ('provincia', models.CharField(blank=True, max_length=25, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=25, null=True)),
                ('calle', models.CharField(blank=True, max_length=25, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_negocio', to='negocio.categorianegocio')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocio_seguidor', to='negocio.negocio')),
                ('usuario', models.ManyToManyField(related_name='perfil_seguidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacion')),
                ('votos', models.IntegerField(blank=True, default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('precio', models.FloatField(default=0.0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producto', to='negocio.categoriaproducto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='negocio',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='negocio.Producto'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidores_negocio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=negocio.models.nombreArchivo)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_galeria', to='negocio.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
